stateDiagram-v2
  direction TB
  state "Concluído" as Concluido
  state "Liberado apresentação" as Liberado
  [*] --> Novo : criação automática
  Novo --> Pendente
  Novo --> Desenvolvimento
  Novo --> Cancelado
  Pendente --> Desenvolvimento
  Desenvolvimento --> Pendente
  Desenvolvimento --> Cancelado
  Desenvolvimento --> Concluido
  Concluido --> Desenvolvimento
  Concluido --> Finalizado
  Concluido --> Liberado
  Liberado --> Avaliado : automático
  Cancelado --> [*]
  Finalizado --> [*]
  Avaliado --> [*]
